public class ContohVariabel10 {
public static void main(String[] args) {
String salahSatuHobySayaAdalah = "Melukis";
boolean isPandai = true;
char jeniskelamin = 'P';
byte umurSayaSekarang = 19;
double ipk = 3.80, tinggi = 1.63;
System.out.println(salahSatuHobySayaAdalah);
System.out.println("Apakah pandai? " + isPandai);
System.out.println("Jenis Kelamin: " + jeniskelamin);
System.out.println("Umurku saat ini: " + umurSayaSekarang);
System.out.println(String.format("Saya beripk %s, dengan tinggi badan %s", ipk, tinggi));
}
}